# Generated by Django 4.2.7 on 2023-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default='YYYY-MM-DD'),
            preserve_default=False,
        ),
    ]
