# Generated by Django 4.2.7 on 2023-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='img', upload_to='downloads'),
            preserve_default=False,
        ),
    ]
